FROM ubuntu:20.04
MAINTAINER 
RUN apt-get update
RUN apt install default-jre
apt install default-jdk
apt-get install ant
apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libboost-filesystem-dev libboost-thread-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev

apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config

apt-get install thrift-compiler


apt install python3-pip
pip3 install thrift

EXPOSE 